[project]
name = "video"
version = "0.1.0"
description = ""
authors = [{name="Giacomo Arianna",email="ariannagiacomo@gmail.com"}]
readme = "README.md"
packages = [{include = "video", from = "src"}]

[project.poetry.dependencies]
python = "^3.13"
quart = "^0.19.6"
quart-babel = "^1.0.7"
pymodbustcp = "^0.3.0"
pymodbus = "^3.7.4"
quart-schema = "^0.20.0"
gpiozero = "^2.0.1"
smbus2 = "^0.5.0"
pyserial = "^3.5"
hypercorn = "^0.17.3"
msgspec = "^0.21.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
