[project]
name = "video"
version = "0.1.0"
description = "Manage iot"
authors = [
    {name = "jackarian",email = "ariannagiacomo@gmail.com"}
]
license = "Apache Licence 2.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "quart (>=0.21.0,<0.22.0)",
    "hypercorn (>=0.18.0,<0.19.0)",
    "msgspec (>=0.21.1,<0.22.0)",
    "quart-babel (>=1.0.7,<2.0.0)",
    "pymodbus (>=3.14.0,<4.0.0)",
    "quart-schema (>=0.23.0,<0.24.0)",
    "gpiozero (>=2.0.1.post3,<3.0.0)",
    "smbus2 (>=0.6.1,<0.7.0)",
    "pyserial (>=3.5,<4.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
